# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-21 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190121_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordergoods',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordergoods',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderGoods',
        ),
        migrations.DeleteModel(
            name='OrderInfo',
        ),
    ]
